version: '3.9'

networks:
  postgres-network:
    external: true

volumes:
  postgresdb:
    external: true

services:
  postgredb:
    image: postgres
    ports: 
      - 5432:5432
    volumes:
      - postgresdb:/var/lib/postgresql/data
    networks : 
      - postgres-network
    environment:
      - POSTGRES_PASSWORD=Postgres2018!
  web-pgadmin: 
    image: dpage/pgadmin4
    ports: 
      - 15432:80
    networks : 
      - postgres-network
    environment:
      - PGADMIN_DEFAULT_EMAIL=yurialcantara03@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=PgAdmin2018!
    depends_on:
    - postgredb
  app:
    image: app-1.0.0
    ports:
      - 8080:8080
    links:
      - postgredb:postgredb
    networks:
      - postgres-network
    environment:
     - DATA_BASE_URL=jdbc:postgresql://postgredb:5432/cadastrodb
    depends_on:
      - postgredb
      - web-pgadmin
